use super::*;
use crate::genesis::tests as fixture;
use ed25519_zebra::SigningKey;

struct Signer(SigningKey);
impl ConsensusSigner for Signer {
    fn validator_id(&self) -> protocol_types::ValidatorId {
        protocol_types::ValidatorId::new(fixture::sender())
    }
    fn signature_scheme(&self) -> protocol_types::SignatureSchemeId {
        protocol_types::SignatureSchemeId::Ed25519
    }
    fn sign_framed(&self, bytes: &[u8]) -> Result<Vec<u8>, String> {
        let signature: [u8; 64] = self.0.sign(bytes).into();
        Ok(signature.to_vec())
    }
}

fn policy() -> OrderedEconomicsPolicy {
    let (mut manifest, _, _, _, _) = fixture::build_fixture();
    manifest.commitment_profile = crate::logical_generation::CommitmentProfile::CausalAdmission;
    manifest.minimum_freeze_block_height = 1;
    fixture::resign_manifest(&mut manifest);
    let resolver: HashSuiteResolver = fixture::resolver();
    let digest: Digest32 =
        crate::genesis::genesis_manifest_commitment(&resolver, &manifest).unwrap();
    let root: crate::genesis::VerifiedGenesisRoot =
        crate::genesis::VerifiedGenesisRoot::verify_bytes(
            &resolver,
            &crate::genesis::encode_genesis_manifest(&manifest).unwrap(),
            digest.bytes(),
            manifest.context(),
        )
        .unwrap();
    OrderedEconomicsPolicy::from_genesis_root(&root, fixture::domain()).unwrap()
}

// Real signed-genesis one-validator consensus rounds. Every proposal,
// vote, QC and committed proof is generated by the owning engine and
// re-verified; these focused ancestry tests do not accept a Seal or seed
// any durable outcome, receipt or barrier.
fn certify_proposal(
    policy: &OrderedEconomicsPolicy,
    state: &ConsensusState,
    proposal: &ConsensusProposal,
) -> ConsensusOutput {
    let signer: Signer = Signer(fixture::key());
    let proposal_output: ConsensusOutput = policy
        .engine()
        .on_event(
            state,
            ConsensusEvent::Proposal(proposal.clone()),
            &signer,
            &Ed25519ConsensusVerifier,
        )
        .unwrap();
    let vote: consensus::ConsensusVote = proposal_output
        .outbound_messages
        .iter()
        .find_map(|message: &ConsensusMessage| match message {
            ConsensusMessage::Vote(vote) => Some(vote.clone()),
            _ => None,
        })
        .unwrap();
    let output: ConsensusOutput = policy
        .engine()
        .on_event(
            &proposal_output.state,
            ConsensusEvent::Vote(vote),
            &signer,
            &Ed25519ConsensusVerifier,
        )
        .unwrap();
    policy
        .engine()
        .validate_state(&output.state, &Ed25519ConsensusVerifier)
        .unwrap();
    output
}

fn boundary(
    policy: &OrderedEconomicsPolicy,
    proof: &consensus::CommittedBlockProof,
) -> OrderedHistoryHeightDescriptor {
    let block: CommittedBlock =
        super::super::ordered_history::verified_committed_block(policy, proof).unwrap();
    let bytes: Vec<u8> = consensus::encode_committed_block_proof(proof).unwrap();
    OrderedHistoryHeightDescriptor {
        identity: OrderedHistoryIdentity {
            context: policy.context().clone(),
            domain: policy.domain(),
            genesis_digest: policy.genesis_digest(),
            anchor: policy.anchor(),
            through_height: block.height,
            through_view: block.view,
            through_digest: block.digest,
        },
        height: block.height,
        view: block.view,
        block_digest: block.digest,
        components: vec![OrderedHistoryComponentRef {
            kind: OrderedHistoryComponentKind::CommitProof,
            length: u64::try_from(bytes.len()).unwrap(),
            digest: super::super::ordered_history::ordered_history_component_digest(policy, &bytes)
                .unwrap(),
        }],
    }
}

fn empty_prefix(
    policy: &OrderedEconomicsPolicy,
    mut state: ConsensusState,
    rounds: usize,
) -> (ConsensusState, OrderedHistoryHeightDescriptor) {
    let signer: Signer = Signer(fixture::key());
    let mut last: Option<OrderedHistoryHeightDescriptor> = None;
    for _ in 0..rounds {
        let proposal: ConsensusProposal = policy
            .engine()
            .propose(&state, Vec::new(), &signer)
            .unwrap();
        let output: ConsensusOutput = certify_proposal(policy, &state, &proposal);
        if let Some(proof) = output.committed_proofs.last() {
            last = Some(boundary(policy, proof));
        }
        state = output.state;
    }
    (state, last.unwrap())
}

#[test]
fn genuine_empty_selected_suffix_reaches_the_exact_committed_boundary() {
    let policy: OrderedEconomicsPolicy = policy();
    let (state, boundary) = empty_prefix(&policy, policy.engine().genesis_state(0), 4);
    assert!(require_seal_selected_ancestry(&policy, &state, &state.high_qc, &boundary).is_ok());
}

#[test]
fn genuine_selected_nonempty_suffix_requires_catchup() {
    let policy: OrderedEconomicsPolicy = policy();
    let (state, _) = empty_prefix(&policy, policy.engine().genesis_state(0), 3);
    let candidate: Digest32 = policy
        .resolver()
        .hash_for_purpose(
            policy.context().epoch(),
            HashPurpose::NodeEvent,
            b"selected-candidate",
        )
        .unwrap();
    let proposal: ConsensusProposal = policy
        .engine()
        .propose(&state, vec![candidate], &Signer(fixture::key()))
        .unwrap();
    let output: ConsensusOutput = certify_proposal(&policy, &state, &proposal);
    let boundary: OrderedHistoryHeightDescriptor =
        boundary(&policy, output.committed_proofs.last().unwrap());
    assert!(matches!(
        require_seal_selected_ancestry(&policy, &output.state, &output.state.high_qc, &boundary),
        Err(OrderedEconomicsError::Prerequisite(
            "Seal selected ancestor carries a candidate; declared catch-up required"
        ))
    ));
}

#[test]
fn legally_superseded_nonempty_fork_does_not_close_the_empty_selected_branch() {
    let policy: OrderedEconomicsPolicy = policy();
    let signer: Signer = Signer(fixture::key());
    let (base, _) = empty_prefix(&policy, policy.engine().genesis_state(0), 3);
    let candidate: Digest32 = policy
        .resolver()
        .hash_for_purpose(
            policy.context().epoch(),
            HashPurpose::NodeEvent,
            b"superseded-candidate",
        )
        .unwrap();
    let old: ConsensusProposal = policy
        .engine()
        .propose(&base, vec![candidate], &signer)
        .unwrap();
    let old_output: ConsensusOutput = certify_proposal(&policy, &base, &old);
    let boundary: OrderedHistoryHeightDescriptor =
        boundary(&policy, old_output.committed_proofs.last().unwrap());
    let advanced: ConsensusOutput = policy
        .engine()
        .on_event(
            &base,
            ConsensusEvent::Tick {
                now_unix_millis: base.view_deadline_unix_millis,
            },
            &signer,
            &Ed25519ConsensusVerifier,
        )
        .unwrap();
    let selected: ConsensusProposal = policy
        .engine()
        .propose(&advanced.state, Vec::new(), &signer)
        .unwrap();
    let output: ConsensusOutput = certify_proposal(&policy, &old_output.state, &selected);
    let old_digest: Digest32 = policy.engine().proposal_digest(&old).unwrap();
    assert!(
        !output
            .state
            .known_proposal(&old_digest)
            .unwrap()
            .transactions
            .is_empty()
    );
    assert!(
        require_seal_selected_ancestry(&policy, &output.state, &output.state.high_qc, &boundary)
            .is_ok()
    );
}

#[test]
fn independently_authenticated_alternative_boundary_and_missing_branch_stop() {
    let policy: OrderedEconomicsPolicy = policy();
    let (first, first_boundary) = empty_prefix(&policy, policy.engine().genesis_state(0), 4);
    let genesis: ConsensusState = policy.engine().genesis_state(0);
    let advanced: ConsensusOutput = policy
        .engine()
        .on_event(
            &genesis,
            ConsensusEvent::Tick {
                now_unix_millis: genesis.view_deadline_unix_millis,
            },
            &Signer(fixture::key()),
            &Ed25519ConsensusVerifier,
        )
        .unwrap();
    // Alternative valid delivery chronology starts at view 2. No durable
    // history is rewritten or alternative outcome installed.
    let (second, second_boundary) = empty_prefix(&policy, advanced.state, 4);
    assert_eq!(first_boundary.height, second_boundary.height);
    assert!(matches!(
        require_seal_selected_ancestry(&policy, &second, &second.high_qc, &first_boundary),
        Err(OrderedEconomicsError::Prerequisite(
            "Seal selected branch forks at the committed boundary; catch-up required"
        ))
    ));
    assert!(matches!(
        require_seal_selected_ancestry(&policy, &second, &first.high_qc, &second_boundary),
        Err(OrderedEconomicsError::Prerequisite(
            "Seal selected ancestor is missing; declared catch-up required"
        ))
    ));
    let mut wrong_view: OrderedHistoryHeightDescriptor = first_boundary.clone();
    wrong_view.view = wrong_view.view.checked_add(1).unwrap();
    assert!(matches!(
        require_seal_selected_ancestry(&policy, &first, &first.high_qc, &wrong_view),
        Err(OrderedEconomicsError::Prerequisite(
            "Seal selected branch forks at the committed boundary; catch-up required"
        ))
    ));
}
