[package]
name = "native-http"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
abi.workspace = true
axum.workspace = true
canonical-encoding.workspace = true
execution.workspace = true
fees.workspace = true
hashing.workspace = true
hyper.workspace = true
hyper-util.workspace = true
http-body-util.workspace = true
node-core.workspace = true
node-wire.workspace = true
objects.workspace = true
protocol-config.workspace = true
protocol-types.workspace = true
runtime.workspace = true
tokio.workspace = true
tower.workspace = true

[dev-dependencies]
abi.workspace = true
crypto.workspace = true
ed25519-zebra.workspace = true
runtime-sqlite.workspace = true
standard-assets.workspace = true
system-modules.workspace = true
wat.workspace = true
