/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.certified.jsonc --include-runtime=false --strict-vars=false --env-interface=CertifiedRelayEnv certified-configuration.d.ts` (hash: 96f44e8a48c49abe6b6ee2c28867d92e)
interface __BaseEnv_CertifiedRelayEnv {
	SUNRISE_NODE_CORE_URL: string;
	SUNRISE_NODE_CORE_BEARER_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/certified");
	}
	interface Env extends __BaseEnv_CertifiedRelayEnv {}
}
interface CertifiedRelayEnv extends __BaseEnv_CertifiedRelayEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUNRISE_NODE_CORE_URL" | "SUNRISE_NODE_CORE_BEARER_TOKEN">> {}
}
