/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.validator.jsonc --include-runtime=false --strict-vars=false --env-interface=ValidatorEnv validator-configuration.d.ts` (hash: f0587fc6ce740e641633473730535ec0)
interface __BaseEnv_ValidatorEnv {
	VALIDATOR_ACTOR_NAME: string;
	VALIDATOR_GENESIS: string;
	VALIDATOR_CONFIG: string;
	VALIDATOR_BEARER_TOKEN: string;
	VALIDATOR_STATE: DurableObjectNamespace<import("./src/validator/index").ValidatorObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/validator/index");
		durableNamespaces: "ValidatorObject";
	}
	interface Env extends __BaseEnv_ValidatorEnv {}
}
interface ValidatorEnv extends __BaseEnv_ValidatorEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VALIDATOR_ACTOR_NAME" | "VALIDATOR_GENESIS" | "VALIDATOR_CONFIG" | "VALIDATOR_BEARER_TOKEN">> {}
}
