[package]
name = "public-standard-asset"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
abi.workspace = true
canonical-encoding.workspace = true
objects.workspace = true
protocol-types.workspace = true
wat.workspace = true

[dev-dependencies]
execution.workspace = true
hashing.workspace = true
ed25519-zebra.workspace = true
sha2.workspace = true
