[package]
name = "runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
durable-conformance = ["dep:hashing"]

[dependencies]
canonical-encoding.workspace = true
hashing = { workspace = true, optional = true }
objects.workspace = true
protocol-types.workspace = true

[dev-dependencies]
hashing.workspace = true
