[package]
name = "sunrise-edge-operator"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hashing.workspace = true
node-core.workspace = true
postgres.workspace = true
postgres_rustls.workspace = true
protocol-types.workspace = true
r2d2_postgres.workspace = true
runtime.workspace = true
runtime-postgres.workspace = true
rustls.workspace = true
