[package]
name = "sunrise-edge-devnet"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
abi.workspace = true
axum.workspace = true
canonical-encoding.workspace = true
crypto.workspace = true
execution.workspace = true
fees.workspace = true
hashing.workspace = true
native-http.workspace = true
node-core.workspace = true
objects.workspace = true
protocol-config.workspace = true
protocol-types.workspace = true
protocol-upgrades.workspace = true
runtime.workspace = true
runtime-sqlite.workspace = true
standard-assets.workspace = true
system-modules.workspace = true
tokio = { workspace = true, features = ["signal"] }

[dev-dependencies]
ed25519-zebra.workspace = true
wat.workspace = true
