use abi::package_types::PackageOrigin;
use canonical_encoding::{CanonicalStruct, decode_canonical_frame, encode_digest32};
use crypto::{
    SignatureDomain, SignatureMessageType, decode_signature_frame, frame_signature_message,
};
use ed25519_zebra::{SigningKey, VerificationKey};
use execution::publication::PublicationError as E;
use execution::publication::*;
use hashing::HashSuiteResolver;
use protocol_types::{
    ChainId, Digest32, Epoch, HashAlgorithmId, HashSuite, HashSuiteId, HashSuiteSchedule,
    ProtocolVersion, SignatureSchemeId,
};
use sha2::{Digest as _, Sha256};

fn key() -> SigningKey {
    SigningKey::from([7; 32])
}
fn publisher() -> [u8; 32] {
    VerificationKey::from(&key()).into()
}
fn context(chain: &str, protocol: u32, epoch: u64) -> PublicationContext {
    PublicationContext::new(
        ChainId::new(chain).unwrap(),
        ProtocolVersion::new(protocol),
        Epoch::new(epoch),
    )
    .unwrap()
}
fn resolver(chain: &str, protocol: u32) -> HashSuiteResolver {
    HashSuiteResolver::new(
        ChainId::new(chain).unwrap(),
        ProtocolVersion::new(protocol),
        vec![
            HashSuiteSchedule {
                activation_epoch: Epoch::new(0),
                suite: HashSuite::genesis(),
            },
            HashSuiteSchedule {
                activation_epoch: Epoch::new(5),
                suite: HashSuite::uniform(HashSuiteId::new(2), HashAlgorithmId::Sha3_256),
            },
        ],
    )
    .unwrap()
}
fn semantics() -> Digest32 {
    Digest32::new(HashAlgorithmId::Sha2_256, [0x66; 32])
}
fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}
fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}
fn parts() -> ArtifactParts {
    ArtifactParts {
        context: context("test", 1, 0),
        origin: PackageOrigin::unverified(ChainId::new("test").unwrap(), publisher(), [0x22; 32])
            .unwrap(),
        revision: 1,
        wasm_profile: 1,
        semantics: semantics(),
        wasm: unhex(
            "0061736d0100000001040160000003020100050401010102071002066d656d6f727902000372756e00000a040102000b",
        ),
        unverified_abi: b"opaque-abi".to_vec(),
        exports: vec!["run".to_string()],
        unverified_dependencies: vec![],
    }
}
fn dependency(seed: u8) -> UnverifiedDependencyRef {
    UnverifiedDependencyRef::new(
        PackageOrigin::unverified(ChainId::new("test").unwrap(), [0x44; 32], [seed; 32]).unwrap(),
        1,
        context("test", 1, 0),
        Digest32::new(HashAlgorithmId::Sha2_256, [0x55; 32]),
    )
    .unwrap()
}
fn signed(artifact: CodeArtifact, nonce: u64) -> PublicationRequest {
    let r: HashSuiteResolver = resolver(
        artifact.context().chain_id().as_str(),
        artifact.context().protocol_version().get(),
    );
    let digest: Digest32 = artifact_commitment(&r, artifact.context(), &artifact).unwrap();
    let frame: Vec<u8> =
        publication_signing_frame(&r, artifact.context(), &artifact, nonce).unwrap();
    PublicationRequest::new(artifact, nonce, digest, key().sign(&frame).into())
}
fn authenticate(request: PublicationRequest) -> Result<AuthenticatedPublicationCandidate, E> {
    authenticate_publication(
        &resolver("test", 1),
        &context("test", 1, 0),
        &semantics(),
        request,
    )
}
fn replace_field(bytes: &[u8], field: u16, value: Vec<u8>) -> Vec<u8> {
    let source = decode_canonical_frame(bytes).unwrap();
    let mut output: CanonicalStruct = CanonicalStruct::new(source.type_id(), source.version());
    for id in 1..=128 {
        if id == field {
            output.field_bytes(id, value.clone()).unwrap();
        } else if let Some(existing) = source.field(id) {
            output.field_bytes(id, existing).unwrap();
        }
    }
    output.finish().unwrap()
}
fn list(id: u16, count: u16, values: Vec<Vec<u8>>) -> Vec<u8> {
    let mut frame: CanonicalStruct = CanonicalStruct::new(id, 1);
    frame.field_u16(1, count).unwrap();
    for (index, value) in values.into_iter().enumerate() {
        frame
            .field_bytes(2 + u16::try_from(index).unwrap(), value)
            .unwrap();
    }
    frame.finish().unwrap()
}

#[test]
fn independent_canonical_commitment_and_ed25519_vectors() {
    // Reconstructed independently with Node Buffer canonical framing and
    // node:crypto SHA256/Ed25519, not generated by these Rust codecs/signers.
    let artifact: CodeArtifact = CodeArtifact::new(parts()).unwrap();
    assert_eq!(
        hex(&publisher()),
        "ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c"
    );
    assert_eq!(
        hex(&encode_publication_context(artifact.context()).unwrap()),
        "534e524501630100030001000400000074657374020004000000010000000300080000000000000000000000"
    );
    let encoded: Vec<u8> = encode_code_artifact(&artifact).unwrap();
    assert_eq!(encoded.len(), 383);
    assert_eq!(decode_code_artifact(&encoded).unwrap(), artifact);
    let request: PublicationRequest = signed(artifact, 9);
    assert_eq!(
        hex(&request.artifact_digest().bytes()),
        "be4ed00dd708396626c10f02a725eadb31346c6b2a5311a4049135e01aeaee65"
    );
    assert_eq!(
        hex(request.signature()),
        "2a6272cffe0589a1dc41305d22c657e4e236ce5b689546e09db331b0737d6851b75c92dc539c01ad0bd118c606f96c0f66b2177fe4a822c1a21d92e4cd09ad08"
    );
    let frame: Vec<u8> = publication_signing_frame(
        &resolver("test", 1),
        request.artifact().context(),
        request.artifact(),
        9,
    )
    .unwrap();
    assert_eq!(
        hex(&Sha256::digest(&frame)),
        "339fafe0bced857fde07dddf0a77f1edb419d534227a458ccd8a08b7fd9a848f"
    );
    let wire: Vec<u8> = encode_publication_request(&request).unwrap();
    assert_eq!(decode_publication_request(&wire).unwrap(), request);
    let candidate = authenticate(decode_publication_request(&wire).unwrap()).unwrap();
    assert_eq!(candidate.request(), &request);
    // This is explicitly NOT typed-ABI admission: these arbitrary bytes
    // authenticate but no execution/persistence API consumes the witness.
    assert_eq!(
        candidate.request().artifact().unverified_abi(),
        b"opaque-abi"
    );
    assert_eq!(
        authenticate(request.clone()).unwrap(),
        authenticate(request).unwrap()
    );
}

#[test]
fn all_artifact_bytes_and_nonce_are_bound_even_with_recomputed_digest() {
    let original: PublicationRequest = signed(CodeArtifact::new(parts()).unwrap(), 9);
    let mut changes: Vec<ArtifactParts> = vec![];
    let mut p = parts();
    p.unverified_abi.push(0);
    changes.push(p);
    let mut p = parts();
    p.wasm =
        wat::parse_str("(module (memory (export \"memory\") 1 2) (func (export \"run\") nop))")
            .unwrap();
    changes.push(p);
    let mut p = parts();
    p.unverified_dependencies.push(dependency(1));
    changes.push(p);
    let mut p = parts();
    p.exports = vec!["other".to_string()];
    changes.push(p);
    let mut p = parts();
    p.origin =
        PackageOrigin::unverified(ChainId::new("test").unwrap(), publisher(), [0x23; 32]).unwrap();
    changes.push(p);
    for p in changes {
        let changed: CodeArtifact = CodeArtifact::new(p).unwrap();
        assert!(matches!(
            authenticate(PublicationRequest::new(
                changed.clone(),
                9,
                *original.artifact_digest(),
                *original.signature()
            )),
            Err(E::CommitmentMismatch)
        ));
        let digest =
            artifact_commitment(&resolver("test", 1), &context("test", 1, 0), &changed).unwrap();
        assert!(matches!(
            authenticate(PublicationRequest::new(
                changed,
                9,
                digest,
                *original.signature()
            )),
            Err(E::InvalidSignature)
        ));
    }
    assert!(matches!(
        authenticate(PublicationRequest::new(
            original.artifact().clone(),
            10,
            *original.artifact_digest(),
            *original.signature()
        )),
        Err(E::InvalidSignature)
    ));
    let selected_algo = Digest32::new(
        HashAlgorithmId::Sha3_256,
        original.artifact_digest().bytes(),
    );
    assert!(matches!(
        authenticate(PublicationRequest::new(
            original.artifact().clone(),
            9,
            selected_algo,
            *original.signature()
        )),
        Err(E::CommitmentMismatch)
    ));
}

#[test]
fn dependencies_are_exact_unverified_claims_not_authority() {
    let mut p = parts();
    p.unverified_dependencies = vec![dependency(1)];
    let original = signed(CodeArtifact::new(p).unwrap(), 9);
    assert!(authenticate(original.clone()).is_ok()); // no resolver consulted
    let base = dependency(1);
    for changed in [
        UnverifiedDependencyRef::new(
            base.origin().clone(),
            2,
            base.context().clone(),
            *base.artifact_digest(),
        )
        .unwrap(),
        UnverifiedDependencyRef::new(
            base.origin().clone(),
            1,
            context("test", 2, 99),
            *base.artifact_digest(),
        )
        .unwrap(),
        UnverifiedDependencyRef::new(
            base.origin().clone(),
            1,
            base.context().clone(),
            Digest32::new(HashAlgorithmId::Sha2_256, [0x56; 32]),
        )
        .unwrap(),
    ] {
        let mut p = parts();
        p.unverified_dependencies = vec![changed.clone()];
        let artifact = CodeArtifact::new(p).unwrap();
        assert_eq!(
            decode_dependency_ref(&encode_dependency_ref(&changed).unwrap()).unwrap(),
            changed
        );
        let digest =
            artifact_commitment(&resolver("test", 1), &context("test", 1, 0), &artifact).unwrap();
        assert!(matches!(
            authenticate(PublicationRequest::new(
                artifact,
                9,
                digest,
                *original.signature()
            )),
            Err(E::InvalidSignature)
        ));
    }
}

#[test]
fn signature_family_publisher_and_strict_key_policy_cannot_be_substituted() {
    let original = signed(CodeArtifact::new(parts()).unwrap(), 9);
    let frame = publication_signing_frame(
        &resolver("test", 1),
        &context("test", 1, 0),
        original.artifact(),
        9,
    )
    .unwrap();
    let decoded = decode_signature_frame(&frame).unwrap();
    assert_eq!(decoded.message_type, "CreatePackage");
    let wrong_domain = SignatureDomain {
        chain_id: ChainId::new("test").unwrap(),
        protocol_version: ProtocolVersion::new(1),
        epoch: Epoch::new(0),
        message_type: SignatureMessageType::new("SubmitTransaction").unwrap(),
        signature_scheme_id: SignatureSchemeId::Ed25519,
    };
    let different_frame = frame_signature_message(&wrong_domain, decoded.payload).unwrap();
    let wrong_key = SigningKey::from([8; 32]);
    for sig in [
        key().sign(&different_frame).into(),
        wrong_key.sign(&frame).into(),
        key().sign(original.artifact().wasm()).into(),
    ] {
        assert!(matches!(
            authenticate(PublicationRequest::new(
                original.artifact().clone(),
                9,
                *original.artifact_digest(),
                sig
            )),
            Err(E::InvalidSignature)
        ));
    }
    let mut identity = [0; 32];
    identity[0] = 1;
    for non_owning in [identity, [0; 32], [0xff; 32]] {
        let mut p = parts();
        p.origin = PackageOrigin::unverified(ChainId::new("test").unwrap(), non_owning, [0x22; 32])
            .unwrap();
        let artifact = CodeArtifact::new(p).unwrap();
        let digest =
            artifact_commitment(&resolver("test", 1), &context("test", 1, 0), &artifact).unwrap();
        let mut universal_signature = [0; 64];
        universal_signature[0] = 1;
        assert!(matches!(
            authenticate(PublicationRequest::new(
                artifact,
                9,
                digest,
                universal_signature
            )),
            Err(E::Owner(_))
        ));
    }
}

#[test]
fn trusted_context_and_original_hash_epoch_are_not_taken_from_request() {
    let original = signed(CodeArtifact::new(parts()).unwrap(), 9);
    for expected in [
        context("other", 1, 0),
        context("test", 2, 0),
        context("test", 1, 1),
    ] {
        assert!(
            authenticate_publication(
                &resolver(
                    expected.chain_id().as_str(),
                    expected.protocol_version().get()
                ),
                &expected,
                &semantics(),
                original.clone()
            )
            .is_err()
        );
    }
    assert!(matches!(
        authenticate_publication(
            &resolver("test", 2),
            &context("test", 1, 0),
            &semantics(),
            original.clone()
        ),
        Err(E::ContextMismatch)
    ));
    assert!(matches!(
        authenticate_publication(
            &resolver("test", 1),
            &context("test", 1, 0),
            &Digest32::new(HashAlgorithmId::Sha2_256, [0x67; 32]),
            original.clone()
        ),
        Err(E::SemanticsMismatch)
    ));
    let mut p = parts();
    p.context = context("test", 1, 5);
    let rotated = signed(CodeArtifact::new(p).unwrap(), 9);
    assert_eq!(
        rotated.artifact_digest().algorithm(),
        HashAlgorithmId::Sha3_256
    );
    assert_ne!(rotated.artifact_digest(), original.artifact_digest());
    assert!(
        authenticate_publication(
            &resolver("test", 1),
            &context("test", 1, 5),
            &semantics(),
            rotated.clone()
        )
        .is_ok()
    );
    assert!(authenticate(rotated).is_err());
    // Recorded epoch 0 still verifies with the trusted original context;
    // it is never rehashed at epoch 5 just because history now contains it.
    assert!(authenticate(original).is_ok());
}

#[test]
fn signature_precedes_nonexecuting_wasm_validation() {
    let mut p = parts();
    p.wasm = b"not wasm".to_vec();
    let request = signed(CodeArtifact::new(p).unwrap(), 9);
    let unsigned = PublicationRequest::new(
        request.artifact().clone(),
        9,
        *request.artifact_digest(),
        [0; 64],
    );
    assert!(matches!(authenticate(unsigned), Err(E::InvalidSignature)));
    assert!(matches!(authenticate(request), Err(E::Wasm(_))));
    for wasm in [
        "(module (memory (export \"memory\") 1 2) (func $start (loop br 0)) (start $start) (func (export \"run\")))",
        "(module (memory (export \"memory\") 1 2) (func (export \"wrong\")))",
    ] {
        let mut p = parts();
        p.wasm = wat::parse_str(wasm).unwrap();
        assert!(matches!(
            authenticate(signed(CodeArtifact::new(p).unwrap(), 9)),
            Err(E::Wasm(_))
        ));
    }
    let mut p = parts();
    p.wasm = wat::parse_str(
        "(module (memory (export \"memory\") 1 2) (func (export \"run\") (loop br 0)))",
    )
    .unwrap();
    assert!(authenticate(signed(CodeArtifact::new(p).unwrap(), 9)).is_ok());
}

#[test]
fn construction_fails_closed_for_unsupported_or_noncanonical_metadata() {
    let mut invalid: Vec<ArtifactParts> = vec![];
    for revision in [0, 2, u64::MAX] {
        let mut p = parts();
        p.revision = revision;
        invalid.push(p);
    }
    for profile in [0, 2, u32::MAX] {
        let mut p = parts();
        p.wasm_profile = profile;
        invalid.push(p);
    }
    for exports in [
        vec![],
        vec!["".to_string()],
        vec!["memory".to_string()],
        vec!["z".to_string(), "a".to_string()],
        vec!["run".to_string(); 2],
        vec!["a".repeat(257)],
        vec!["a".to_string(); 65],
    ] {
        let mut p = parts();
        p.exports = exports;
        invalid.push(p);
    }
    for abi in [vec![], vec![0; MAX_ABI_DECLARATION_BYTES + 1]] {
        let mut p = parts();
        p.unverified_abi = abi;
        invalid.push(p);
    }
    for wasm in [vec![], vec![0; execution::MAX_CONTRACT_WASM_BYTES + 1]] {
        let mut p = parts();
        p.wasm = wasm;
        invalid.push(p);
    }
    let mut p = parts();
    p.context = context("other", 1, 0);
    invalid.push(p);
    for deps in [
        vec![dependency(2), dependency(1)],
        vec![dependency(1); 2],
        vec![dependency(1); 33],
    ] {
        let mut p = parts();
        p.unverified_dependencies = deps;
        invalid.push(p);
    }
    let mut p = parts();
    p.unverified_dependencies = vec![
        UnverifiedDependencyRef::new(p.origin.clone(), 1, p.context.clone(), semantics()).unwrap(),
    ];
    invalid.push(p);
    for p in invalid {
        assert!(CodeArtifact::new(p).is_err());
    }
    assert!(
        UnverifiedDependencyRef::new(
            dependency(1).origin().clone(),
            0,
            context("test", 1, 0),
            semantics()
        )
        .is_err()
    );
    assert!(
        UnverifiedDependencyRef::new(
            dependency(1).origin().clone(),
            1,
            context("other", 1, 0),
            semantics()
        )
        .is_err()
    );
    assert!(
        PublicationContext::new(
            ChainId::new("a".repeat(129)).unwrap(),
            ProtocolVersion::new(1),
            Epoch::new(0)
        )
        .is_err()
    );
    let mut p = parts();
    p.unverified_abi = vec![0; MAX_ABI_DECLARATION_BYTES];
    p.unverified_dependencies = (0..32).map(dependency).collect();
    p.exports = (0..64)
        .map(|i| format!("a{i:02}{}", "x".repeat(253)))
        .collect();
    let boundary = CodeArtifact::new(p).unwrap();
    assert_eq!(
        decode_code_artifact(&encode_code_artifact(&boundary).unwrap()).unwrap(),
        boundary
    );
}

#[test]
fn wire_decoding_rejects_malleability_counts_lengths_and_unknown_fields() {
    let request = signed(CodeArtifact::new(parts()).unwrap(), 9);
    let wire = encode_publication_request(&request).unwrap();
    for end in 0..wire.len() {
        assert!(
            decode_publication_request(&wire[..end]).is_err(),
            "prefix {end}"
        );
    }
    let mut trailing = wire.clone();
    trailing.push(0);
    assert!(decode_publication_request(&trailing).is_err());
    for field in [4, 5] {
        let raw = replace_field(&wire, field, vec![0; 63]);
        assert!(decode_publication_request(&raw).is_err());
    }
    assert!(decode_publication_request(&vec![0; MAX_PUBLICATION_BYTES + 1]).is_err());
    let artifact = encode_code_artifact(request.artifact()).unwrap();
    for (field, value) in [
        (3, 2_u64.to_le_bytes().to_vec()),
        (4, 2_u32.to_le_bytes().to_vec()),
        (7, vec![0; MAX_ABI_DECLARATION_BYTES + 1]),
        (8, list(0x6304, u16::MAX, vec![])),
        (9, list(0x6305, u16::MAX, vec![])),
        (10, vec![]),
    ] {
        assert!(decode_code_artifact(&replace_field(&artifact, field, value)).is_err());
    }
    for names in [
        vec![b"z".to_vec(), b"a".to_vec()],
        vec![b"a".to_vec(); 2],
        vec![vec![0xff]],
        vec![vec![b'a'; 257]],
    ] {
        let count = u16::try_from(names.len()).unwrap();
        assert!(
            decode_code_artifact(&replace_field(&artifact, 8, list(0x6304, count, names))).is_err()
        );
    }
    let deps = vec![
        encode_dependency_ref(&dependency(2)).unwrap(),
        encode_dependency_ref(&dependency(1)).unwrap(),
    ];
    assert!(decode_code_artifact(&replace_field(&artifact, 9, list(0x6305, 2, deps))).is_err());
    for original in [
        encode_publication_context(request.artifact().context()).unwrap(),
        encode_dependency_ref(&dependency(1)).unwrap(),
        artifact.clone(),
        wire.clone(),
    ] {
        for id in [2_u16, 3] {
            let mut altered = original.clone();
            altered[10..12].copy_from_slice(&id.to_le_bytes());
            assert!(decode_canonical_frame(&altered).is_err());
        }
    }
    for offset in [4, 6] {
        let mut wrong = wire.clone();
        wrong[offset] = 0xff;
        assert!(decode_publication_request(&wrong).is_err());
    }
    let mut unknown_digest = encode_digest32(request.artifact_digest()).unwrap();
    unknown_digest[16..18].copy_from_slice(&u16::MAX.to_le_bytes());
    assert!(decode_publication_request(&replace_field(&wire, 3, unknown_digest)).is_err());
}
