[package]
name = "runtime-sql-durable"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
runtime.workspace = true
protocol-types.workspace = true

[dev-dependencies]
hashing.workspace = true
objects.workspace = true
runtime = { workspace = true, features = ["durable-conformance"] }
