[package]
name = "runtime-sqlite"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
runtime.workspace = true
runtime-sql-durable.workspace = true
rusqlite.workspace = true
protocol-types.workspace = true

[dev-dependencies]
hashing.workspace = true
objects.workspace = true
runtime = { workspace = true, features = ["durable-conformance"] }
