[package]
name = "execution"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
protocol-types = { workspace = true }
canonical-encoding = { workspace = true }
commitments = { workspace = true }
hashing = { workspace = true }
crypto = { workspace = true }
objects = { workspace = true }
abi = { workspace = true }
fees = { workspace = true }
sha2 = { workspace = true }
wasmi = { workspace = true }
wasmi_core = { workspace = true }
wasmparser = { workspace = true }

[dev-dependencies]
ed25519-zebra = { workspace = true }
standard-assets = { workspace = true }
wat = { workspace = true }
