/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=test/validator/wrangler.contract-test.jsonc --include-runtime=false --env-interface=ContractTestEnv test/validator/contract-env.d.ts` (hash: a27551ccfa12378dbb255064239f2eea)
interface __BaseEnv_ContractTestEnv {
	VALIDATOR_ZERO: DurableObjectNamespace<import("./contract-worker").ValidatorZero>;
	VALIDATOR_ONE: DurableObjectNamespace<import("./contract-worker").ValidatorOne>;
	VALIDATOR_TWO: DurableObjectNamespace<import("./contract-worker").ValidatorTwo>;
	VALIDATOR_THREE: DurableObjectNamespace<import("./contract-worker").ValidatorThree>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./contract-worker");
		durableNamespaces: "ValidatorZero" | "ValidatorOne" | "ValidatorTwo" | "ValidatorThree";
	}
	interface Env extends __BaseEnv_ContractTestEnv {}
}
interface ContractTestEnv extends __BaseEnv_ContractTestEnv {}
