/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=test/validator/wrangler.sql-test.jsonc --include-runtime=false --env-interface=SqlProbeEnv test/validator/sql-env.d.ts` (hash: 8ce1003b4511e358b33aff121da16f35)
interface __BaseEnv_SqlProbeEnv {
	SQL_PROBE: DurableObjectNamespace<import("./sql-probe").SqlProbe>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./sql-probe");
		durableNamespaces: "SqlProbe";
	}
	interface Env extends __BaseEnv_SqlProbeEnv {}
}
interface SqlProbeEnv extends __BaseEnv_SqlProbeEnv {}
