[package]
name = "node-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
abi.workspace = true
canonical-encoding.workspace = true
crypto.workspace = true
execution.workspace = true
fees.workspace = true
hashing.workspace = true
objects.workspace = true
protocol-config.workspace = true
protocol-types.workspace = true
runtime.workspace = true
system-modules.workspace = true
standard-assets.workspace = true

[dev-dependencies]
sha2.workspace = true
runtime-sqlite.workspace = true
ed25519-zebra.workspace = true
wat.workspace = true
public-standard-asset = { path = "../../contracts/standard-asset" }
